n = input('Digite algo:')
print('Qual seu tipo primitivo?',(type(n)))
print('É um alfanumerico?',(n.isalnum()))
print('É um alfábetico?',(n.isalpha()))
print('Só tem espaços?',(n.isspace()))
print('Ésta em maiusculas?',(n.isupper()))
print('É um numero?',(n.isnumeric()))
print('Esta em minusculas?',(n.islower()))
print('Esta capitalizada?',(n.istitle()))
